### PR TITLE
Multithread code for reading temperature from sensors

### PR DESCRIPTION
**Pull request by LegyPlegy**
first edition of the sensor code. successfully extracts temperature from /sys/bus/w1/devices/<sensor>, cuts out the value, and prints it out realtime.

TODO: save these data values into arrays for data manipulation. perhaps graphing and statistics are in order?

I am honestly surprised this worked the first time I tried it after I debugged it.

### CODE REVIEW

**Comment by ypsun-umd** [comment]
Couple of things:
- There should not be a separate `README.md`. You should update the `README.md` file directly, instead of creating anew.
- Need 1 empty spaces after`#`. 
- Class name should be like this: `ClassName`, instead of `className`, just for uniformity.
- Separate bigger functions methods into smaller ones, doing this will help both debugging and verifying that the code is correct.
- Some non-pythonic usage
- Need to wait the threads to join after they finish.

Comments should be like this:
```
# This is a comment
```
Note the extra whitespace.

Overall good job.

**Comment by ypsun-umd** [comment]
I have added suggestions in the source code. Please take a look and make changes accordingly. Thanks.

**Comment by ypsun-umd** [comment]
> TODO: save these data values into arrays for data manipulation. perhaps graphing and statistics are in order?
No, these are not needed. These will be implemented on the server side. Here all we need to do is collect data.

**Comment by ypsun-umd** [comment]
Also, we should start writing tests for this particular module.

**Comment by LegyPlegy** [comment]
@ypsun-umd 

I have improved the code as per your suggestions. All suggestions and FIXME's have been taken care of except the implementation of the get_total_sensor_num() method. I will focus on migrating to pathlib & that method early tomorrow morning.

**Notable things:**
I had to edit the super() line underneath the class after some online research in order to fix an error, however I do not fully understand the *args and **kwargs beyond their basic purpose.

I split the methods up a little more so that they are reasonably self contained. I made a note that the "print_therm" method will most likely be rewritten to transmit our temperature data to the server.

I implemented the threading to occur automatically via loops, however I did so using lists with the names of the threads and the serial numbers. This will be changed when I go through and implement the get_total_sensor_num method.

**Pull request closed without merging**
